configs:
  ranges:
    stroke:
      min: 7
      max: 68
    surge:
      min: 30
      max: 60
    sway:
      min: 45
      max: 55
    twist:
      min: 0
      max: 99
    roll:
      min: 30
      max: 60
    pitch:
      min: 30
      max: 60
    valve:
      min: 0
      max: 99
  COM:
    port: COM6
    baudrate: 115200
    debug: true
  factors:
    velocity_factor: 1.4
    speed_factor: 1.4
  patterns:
    full_stroke_with_roll_motion: true
    full_stroke_with_pitch_motion: true
    wild_stroke_and_pitch: true
    long_stroke_1: true
    long_stroke_2: true
    long_stroke_3: true
    long_stroke_4: true
