configs:
  ranges:
    stroke:
      min: 2
      max: 85
    surge:
      min: 30
      max: 60
    sway:
      min: 45
      max: 55
    twist:
      min: 0
      max: 99
    roll:
      min: 20
      max: 80
    pitch:
      min: 30
      max: 60
    valve:
      min: 0
      max: 99
  COM:
    port: COM6
    baudrate: 115200
    debug: true
  factors:
    velocity_factor: 2.1
    speed_factor: 2.1
  patterns:
    full_stroke_with_roll_motion: true
    full_stroke_with_pitch_motion: true
    wild_stroke_and_pitch: true
    long_stroke_1: true
    long_stroke_2: true
