configs:
  ranges:
    stroke:
      min: 10
      max: 80
    surge:
      min: 30
      max: 60
    sway:
      min: 45
      max: 55
    twist:
      min: 0
      max: 99
    roll:
      min: 20
      max: 80
    pitch:
      min: 30
      max: 60
    valve:
      min: 0
      max: 99
  COM:
    port: COM6
    baudrate: 115200
    debug: false
  factors:
    velocity_factor: 2.2
    speed_factor: 2.2
